app:
  port: 10010
  loadDoc: true
  pgURL: 'postgres://postgres@localhost:5432/travis_ci_test'
  query:
    pageSize: 1000
  tcApi: http://qa.topcoder.com/v2
  disableAuth: false
  storageProvider: S3
auth0:
  client: ''
  secret: ''
