app:
  port: 10010
  loadDoc: true
  tcApi: http://qa.topcoder.com/v2
  tcUser: http://dev-lc1-user-service.herokuapp.com
  query:
    pageSize: 1000
datasource:
  pgURL: 'postgres://postgres@localhost:5432/travis_ci_test'
  modelsDirectory: './api/models'
  dbOptions:
    native: true
auth0:
  client: ''
  secret: ''
auth:
  enabled: false
  perms:
    - challengeApp
  paths:
    - httpVerb: DELETE
      path: '*'
    - httpVerb: PUT
      path: '*'
    - httpVerb: POST
      path: '*'