app:
  port: 10010
  loadDoc: true
  pgURL: 'postgres://postgres@localhost:5432/travis_ci_test'
  query:
    pageSize: 1000
  tcApi: http://api.topcoder.com/v2
  disableAuth: false
auth0:
  client: ''
  secret: ''
