app:
  port: 10010
  loadDoc: true
  pgURL: 'postgres://postgres:postgres@cainhuang.com:5432/lc1challengeservice'
  query:
    pageSize: 1000
  tcApi: http://qa.topcoder.com/v2
  tcUser: http://lc1-user-service.herokuapp.com/user
auth:
  enabled: false
  default:
    perms:
      - challengeApp
    enabled: true
  pathOverrides:
    - httpVerb: DELETE
      path: '*'
      enabled: true
      perms:
        - challengeApp
    - httpVerb: PUT
      path: '*'
      enabled: true
    - httpVerb: POST
      path: '*'
      enabled: true
    - httpVerb: GET
      path: '/challenges/:challengeId/files/:fileId/download'
      enabled: true
    - httpVerb: GET
      path: '/challenges/:challengeId/files/:fileId/upload'
      enabled: true
    - httpVerb: GET
      path: '/challenges/:challengeId/submissions/:submissionId/files/:fileId/upload'
      enabled: true
    - httpVerb: GET
      path: '/challenges/:challengeId/submissions/:submissionId/files/:fileId/download'
      enabled: true
